import {
    ManpowerPlanning,
    AddUpdateManpower,
    ManpowerPlanningActions,
    ViewManpowerPlanning,
    ManpowerHeadcount,
    HeadCountRequests,
    HeadCountRequestsActions,
    ViewHeadCountRequests,
} from './ManpowerPlanning';
import DemoGraphics from './DemographicsForm';
import {
    TalentSphereSettingManagement,
    Benefits,
    AddUpdateBenefitForm,
    BenefitStatusTogle,
    BenefitActions,
    RemoteWorkChecklist,
    RemoteWorkChecklistActions,
    RemoteWorkChecklistStatusTogle,
    AddUpdateRemoteWorkChecklistForm,
    JobTypes,
    AddUpdateJobTypeForm,
    JobTypeActions,
    Educations,
    AddUpdateEducationForm,
    EducationActions,
    CareerLevels,
    AddUpdateCareerLevelForm,
    CareerLevelActions,
    InterviewTypes,
    AddUpdateInterviewTypeForm,
    InterviewTypeStatusTogle,
    InterviewTypeActions,
    FeedBackForms,
    AddUpdateFeedBackForm,
    FeedBackFormStatusTogle,
    FeedBackFormActions,
    EmailTemplates,
    AddUpdateEmailTemplateForm,
    EmailTemplateStatusTogle,
    EmailTemplateActions,
    OfferLetterTemplates,
    AddUpdateOfferLetterTemplateForm,
    OfferLetterTemplateStatusTogle,
    OfferLetterTemplateActions,
    ViewEmailTemplateDetail,
    BlacklistReasons,
    AddUpdateBlacklistReasonForm,
    BlacklistReasonStatusTogle,
    BlacklistReasonActions,
} from './SettingManagement';

import {
    RequisitionPlanning,
    PublishedVacancies,
    GenerateRequisition,
    GenerateRequisitionActions,
    PublishVacancyActions,
    ViewPublishedVacancies,
} from './RequisitionPlanning';
import {
    TeamTalentSphere,
    TeamManpowerHeadcount,
    AddUpdateManpowerHeadcountRequest,
    ManpowerHeadCountRequest,
} from './TeamTalentSphere';
import {
    AddUpdateRequisitionRequestForm, RequisitionRequests, ViewRequisitionRequest, RequisitionActions,
    AddUpdateVacancyForm
} from './Requisitions';

import {
    ApplicantManagement,
    AllApplicants,
    ApplicationActions,
    ViewApplicationDetail,
    ResumeBankApplicants,
    UpdateApplicantStatus,
} from './ApplicantManagement';

import {
    InterviewTracker,
    InProgressInterviews,
    InterviewActions,
    ViewInterviewDetails,
    AddInterviewFeedback,
    ViewInterviewFeedback,
} from './InterviewTracker';

import {
    GenerateOffer,
    OfferTracking,
    OfferRequests,
    OfferRequestActions,
} from './OfferTracking';
export {
    OfferRequests,
    AllApplicants,
    GenerateOffer,
    UpdateApplicantStatus,
    InProgressInterviews,
    ViewInterviewDetails,
    InterviewActions,
    ApplicantManagement,
    ApplicationActions,
    ViewApplicationDetail,
    ManpowerPlanning,
    OfferRequestActions,
    AddUpdateManpower,
    ManpowerPlanningActions,
    ViewManpowerPlanning,
    TalentSphereSettingManagement,
    Benefits,
    OfferTracking,
    AddUpdateBenefitForm,
    BenefitStatusTogle,
    BenefitActions,
    RemoteWorkChecklist,
    RemoteWorkChecklistActions,
    RemoteWorkChecklistStatusTogle,
    AddUpdateRemoteWorkChecklistForm,
    JobTypes,
    AddUpdateJobTypeForm,
    JobTypeActions,
    Educations,
    AddUpdateEducationForm,
    EducationActions,
    CareerLevels,
    AddUpdateCareerLevelForm,
    CareerLevelActions,
    ManpowerHeadcount,
    HeadCountRequests,
    HeadCountRequestsActions,
    ViewHeadCountRequests,
    RequisitionPlanning,
    GenerateRequisition,
    GenerateRequisitionActions,
    ViewRequisitionRequest,
    TeamTalentSphere,
    TeamManpowerHeadcount,
    AddUpdateManpowerHeadcountRequest,
    ManpowerHeadCountRequest,
    DemoGraphics,
    RequisitionRequests,
    AddUpdateRequisitionRequestForm,
    RequisitionActions,
    PublishedVacancies,
    AddUpdateVacancyForm,
    PublishVacancyActions,
    ViewPublishedVacancies,
    ResumeBankApplicants,
    InterviewTypes,
    AddUpdateInterviewTypeForm,
    InterviewTypeStatusTogle,
    InterviewTypeActions,
    InterviewTracker,
    FeedBackForms,
    AddUpdateFeedBackForm,
    FeedBackFormStatusTogle,
    FeedBackFormActions,
    EmailTemplates,
    AddUpdateEmailTemplateForm,
    EmailTemplateStatusTogle,
    EmailTemplateActions,
    OfferLetterTemplates,
    AddUpdateOfferLetterTemplateForm,
    OfferLetterTemplateStatusTogle,
    OfferLetterTemplateActions,
    ViewEmailTemplateDetail,
    AddInterviewFeedback,
    ViewInterviewFeedback,
    BlacklistReasons,
    AddUpdateBlacklistReasonForm,
    BlacklistReasonStatusTogle,
    BlacklistReasonActions,
};