import React, { useState } from "react";
import { FileText, Download, Eye, Globe, DollarSign, Calendar, Users } from "lucide-react";
import { Card } from "components/ui/card";
import { Button } from "components/ui/button";
import { Label } from "components/ui/label";
import { Switch } from "components/ui/switch";

const AutoGeneratedPayslips = () => {
  const [selectedCurrency, setSelectedCurrency] = useState("AED");
  const [isGenerating, setIsGenerating] = useState(false);

  const payslips = [
    {
      id: 1,
      employeeId: "EMP001",
      employeeName: "John Doe",
      country: "UAE",
      currency: "AED",
      grossSalary: 15000,
      netSalary: 12000,
      payPeriod: "January 2025",
      generatedAt: "2025-01-21 10:30:00",
      status: "Generated",
      language: "English",
    },
    {
      id: 2,
      employeeId: "EMP002",
      employeeName: "Sarah Johnson",
      country: "UK",
      currency: "GBP",
      grossSalary: 3000,
      netSalary: 2400,
      payPeriod: "January 2025",
      generatedAt: "2025-01-21 10:32:00",
      status: "Generated",
      language: "English",
    },
    {
      id: 3,
      employeeId: "EMP003",
      employeeName: "Ahmed Ali",
      country: "Pakistan",
      currency: "PKR",
      grossSalary: 150000,
      netSalary: 120000,
      payPeriod: "January 2025",
      generatedAt: "2025-01-21 10:35:00",
      status: "Pending",
      language: "Urdu",
    },
    {
      id: 4,
      employeeId: "EMP004",
      employeeName: "Rajesh Kumar",
      country: "India",
      currency: "INR",
      grossSalary: 75000,
      netSalary: 60000,
      payPeriod: "January 2025",
      generatedAt: "2025-01-21 10:38:00",
      status: "Generated",
      language: "Hindi",
    },
  ];

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => setIsGenerating(false), 2000);
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "Generated":
        return "bg-green-100 text-green-700";
      case "Pending":
        return "bg-yellow-100 text-yellow-700";
      case "Failed":
        return "bg-red-100 text-red-700";
      default:
        return "bg-gray-100 text-gray-700";
    }
  };

  return (
    <div className="p-6 space-y-6 bg-gray-50 min-h-screen">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Auto-Generated Payslips</h1>
          <p className="text-gray-600 mt-1">
            Generate payslips in local currency for all employees
          </p>
        </div>
        <Button
          onClick={handleGenerate}
          disabled={isGenerating}
          className="flex items-center gap-2 bg-blue-600 text-white disabled:bg-gray-300"
        >
          {isGenerating ? (
            <>
              <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <FileText className="w-4 h-4" />
              Generate Payslips
            </>
          )}
        </Button>
      </div>

      {/* Generation Settings */}
      <Card className="p-6 bg-white">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Payslip Generation Settings</h2>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <div>
            <Label htmlFor="payPeriod" className="text-sm font-medium text-gray-700">
              Pay Period
            </Label>
            <input
              id="payPeriod"
              type="month"
              className="w-full mt-1 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              defaultValue="2025-01"
            />
          </div>

          <div>
            <Label htmlFor="currency" className="text-sm font-medium text-gray-700">
              Display Currency
            </Label>
            <select
              id="currency"
              value={selectedCurrency}
              onChange={(e) => setSelectedCurrency(e.target.value)}
              className="w-full mt-1 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="AED">AED - UAE Dirham</option>
              <option value="GBP">GBP - British Pound</option>
              <option value="INR">INR - Indian Rupee</option>
              <option value="PKR">PKR - Pakistani Rupee</option>
              <option value="ZAR">ZAR - South African Rand</option>
            </select>
          </div>

          <div>
            <Label htmlFor="language" className="text-sm font-medium text-gray-700">
              Language
            </Label>
            <select
              id="language"
              className="w-full mt-1 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="en">English</option>
              <option value="ar">Arabic</option>
              <option value="hi">Hindi</option>
              <option value="ur">Urdu</option>
              <option value="zu">Zulu</option>
            </select>
          </div>

          <div className="bg-gray-50 p-4 rounded-lg">
            <div className="flex items-center justify-between mb-2">
              <Label className="text-sm font-medium text-gray-700">Auto Email</Label>
              <Switch defaultChecked />
            </div>
            <p className="text-xs text-gray-600">
              Automatically email payslips to employees
            </p>
          </div>
        </div>
      </Card>

      {/* Currency Summary */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="p-6 bg-blue-50 border-blue-200">
          <div className="flex items-center gap-3 mb-2">
            <Globe className="w-6 h-6 text-blue-600" />
            <h3 className="text-sm text-gray-600">Total Countries</h3>
          </div>
          <p className="text-3xl font-bold text-blue-600">4</p>
          <p className="text-sm text-gray-600 mt-1">Active regions</p>
        </Card>

        <Card className="p-6 bg-green-50 border-green-200">
          <div className="flex items-center gap-3 mb-2">
            <Users className="w-6 h-6 text-green-600" />
            <h3 className="text-sm text-gray-600">Total Employees</h3>
          </div>
          <p className="text-3xl font-bold text-green-600">150</p>
          <p className="text-sm text-gray-600 mt-1">Active employees</p>
        </Card>

        <Card className="p-6 bg-purple-50 border-purple-200">
          <div className="flex items-center gap-3 mb-2">
            <FileText className="w-6 h-6 text-purple-600" />
            <h3 className="text-sm text-gray-600">Generated</h3>
          </div>
          <p className="text-3xl font-bold text-purple-600">148</p>
          <p className="text-sm text-gray-600 mt-1">Payslips created</p>
        </Card>

        <Card className="p-6 bg-yellow-50 border-yellow-200">
          <div className="flex items-center gap-3 mb-2">
            <Calendar className="w-6 h-6 text-yellow-600" />
            <h3 className="text-sm text-gray-600">Pending</h3>
          </div>
          <p className="text-3xl font-bold text-yellow-600">2</p>
          <p className="text-sm text-gray-600 mt-1">Awaiting generation</p>
        </Card>
      </div>

      {/* Payslips List */}
      <Card className="p-6 bg-white">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Recent Payslips</h2>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-100">
              <tr>
                <th className="p-3 text-left">Employee</th>
                <th className="p-3 text-left">Country</th>
                <th className="p-3 text-left">Currency</th>
                <th className="p-3 text-left">Gross Salary</th>
                <th className="p-3 text-left">Net Salary</th>
                <th className="p-3 text-left">Language</th>
                <th className="p-3 text-left">Status</th>
                <th className="p-3 text-left">Actions</th>
              </tr>
            </thead>
            <tbody>
              {payslips.map((payslip) => (
                <tr key={payslip.id} className="border-b hover:bg-gray-50">
                  <td className="p-3">
                    <div>
                      <p className="font-semibold">{payslip.employeeName}</p>
                      <p className="text-xs text-gray-500">{payslip.employeeId}</p>
                    </div>
                  </td>
                  <td className="p-3">
                    <div className="flex items-center gap-2">
                      <Globe className="w-4 h-4 text-blue-600" />
                      <span className="font-semibold">{payslip.country}</span>
                    </div>
                  </td>
                  <td className="p-3">
                    <span className="px-2 py-1 bg-gray-100 rounded font-mono text-sm">
                      {payslip.currency}
                    </span>
                  </td>
                  <td className="p-3">
                    <div className="flex items-center gap-1">
                      <DollarSign className="w-4 h-4 text-green-600" />
                      <span className="font-semibold">{payslip.grossSalary.toLocaleString()}</span>
                    </div>
                  </td>
                  <td className="p-3">
                    <div className="flex items-center gap-1">
                      <DollarSign className="w-4 h-4 text-blue-600" />
                      <span className="font-semibold">{payslip.netSalary.toLocaleString()}</span>
                    </div>
                  </td>
                  <td className="p-3">
                    <span className="px-2 py-1 bg-blue-100 text-blue-700 rounded text-xs font-medium">
                      {payslip.language}
                    </span>
                  </td>
                  <td className="p-3">
                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${getStatusColor(payslip.status)}`}>
                      {payslip.status}
                    </span>
                  </td>
                  <td className="p-3">
                    <div className="flex gap-2">
                      <Button className="text-xs bg-blue-100 hover:bg-blue-200 text-blue-700">
                        <Eye className="w-3 h-3 mr-1" />
                        View
                      </Button>
                      <Button className="text-xs bg-green-100 hover:bg-green-200 text-green-700">
                        <Download className="w-3 h-3 mr-1" />
                        Download
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      {/* Currency Conversion Info */}
      <Card className="p-6 bg-blue-50 border-blue-200">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Local Currency Features</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <h3 className="font-semibold text-gray-900 mb-2">Supported Currencies</h3>
            <ul className="text-sm text-gray-700 space-y-1">
              <li>• AED - UAE Dirham (UAE)</li>
              <li>• GBP - British Pound (UK)</li>
              <li>• INR - Indian Rupee (India)</li>
              <li>• PKR - Pakistani Rupee (Pakistan)</li>
              <li>• ZAR - South African Rand (South Africa)</li>
            </ul>
          </div>
          <div>
            <h3 className="font-semibold text-gray-900 mb-2">Localization Features</h3>
            <ul className="text-sm text-gray-700 space-y-1">
              <li>• Country-specific number formatting</li>
              <li>• Local language support</li>
              <li>• Regional date formats</li>
              <li>• Currency symbol placement</li>
              <li>• Local tax calculations</li>
            </ul>
          </div>
        </div>
      </Card>

      {/* Actions */}
      <div className="flex gap-3">
        <Button className="bg-blue-600 text-white">
          <FileText className="w-4 h-4 mr-2" />
          Generate All Payslips
        </Button>
        <Button className="bg-green-600 text-white">
          <Download className="w-4 h-4 mr-2" />
          Bulk Download
        </Button>
        <Button className="bg-gray-200 text-gray-700">View Generation History</Button>
      </div>
    </div>
  );
};

export default AutoGeneratedPayslips;
