server {
    listen 80;
    # server_name staging-hrms.tecbrix.cloud hrms.tecbrix.cloud;
    server_name hrms-production-frontend.mangomoss-a52772ee.uaenorth.azurecontainerapps.io;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
