export const EmployeeExit = {
  id: null,
  employee_id: null,
  emp_name: null,
  serial_number: null,
  request: null,
  exit_date: null,
  exit_interview_date: null,
  exit_interview_notes: null,
  final_working_day: null,
  exit_type: null,
  eligible_for_rehire: null,
  exit_interview_conducted: null,
  exit_interviewer_name: null,
  rehire_eligibility_notes: null,
  exit_checklist: null,
  exit_category: null,
  reason_of_termination: null,
  resignation_letter: null,
  termination_letter: null,
  notice_period: null,
  clearance_report: null,
  clearance_status: null,
  status: null,
  created_at: null,
};

