export const EmployeeTransfer = {
  new_branch: null,
  effective_transfer_date: null,
  reason_of_transfer: null,
  notes: null,
  status: "PENDING",
  transfer_type: "INTERNAL",
  employee_id: null,
  new_department: null,
  new_reporting_manager: null,
  reason_of_rejection:null,
  old_department:null,
  old_branch:null,
  reporting_manager:null,
  hr_manager:null,
};
