const EmployeePersonalInformation = {
  first_name: null,
  last_name: null,
  mobile_no: null,
  serial_number: null,
  date_of_birth: null,
  marital_status: null,
  nationality: null,
  other_email: null,
  nic: null,
  mother_name: null,
  profile_picture: null,
  blood_group: null,
  gender: null,
  father_name: null,
  country_code: null,
  family_book_number: null,
  disbursement_type: null,
  agent_bank_rtn_code: null,
  mol_person_id: null,
  current_address: null,
  residential_address: null,
};
const EmployeeContactInformation = {
  emergency_phone_no: null,
  emergency_first_name: null,
  emergency_last_name: null,
  emergency_relation: null,
  emergency_country_code: null,
  emergency_permanent_address: null,
  emergency_current_address: null,
};

const EmployeeVisaDetails = {
  passport_number: null,
  Passport_Issuance_Country: null,
  Passport_Issuance_Date: null,
  Passport_Expiry_Date: null,
  entry_permit_number: null,
  country_of_visa_issuance: null,
  visa_duration: null,
  uid_number: null,
  living_country_id_no: null,
  dha_id: null,
  card_number: null,
  insurance_policy: null,
  insurance_company: null,
  visa_expiry_date: null,
  visa_issuance_date: null,
  visa_country_entry_date: null,
  visa_country_exit_date: null,
  id_issuance_date: null,
  id_expiry_date: null,
  insurance_active_date: null,
  insurance_expiry_date: null,
  visa_type: null,
  place_of_issuance: null,
  is_passport_applicable: false,
  is_license_applicable: false,
  license_number: null,
  license_Issuance_Country: null,
  license_Issuance_Date: null,
  license_expiry_date: null,
  license_copy: null,
  id: null,
};

const EmployeeCVDetails = {
  cv: null,
  cvName: null,
  existingCVId: null,
};

const EmployeeAcademicRecord = {
  id: null,
  employee_id: null,
  education_level: null,
  program: null,
  institute_name: null,
  edu_start_date: null,
  edu_end_date: null,
  certificate: null,
};

const EmployeeCertifiation = {
  id: null,
  employee_id: null,
  certification_name: null,
  completion_date: null,
  expiry_date: null,
  certification_body: null,
  certification_institute: null,
};

const EmployeeDepartmentInfo = {
  department_name: null,
  department_position: null,
  direct_report: null,
  indirect_report: null,
  department_manager: null,
  employee_type: null,
  employee_work_type: null,
  employee_location: null,
  employee_status: null,
  joining_date: null,
  is_indirect_report_applicable: true,
};

const EmployeeBankDetails = {
  bank_name: null,
  account_title: null,
  account_number: null,
  account_iban: null,
  branch_address: null,
  branch_code: null,
  swift_code: null,
};
const EmployeeInformation = {
  serial_number: null,
  username: null,
  first_name: null,
  last_name: null,
  work_email: null,
  password: null,
  mobile_no: null,
  user_role: null,
  residential_address: null,
  department_name: null,
  country_code: null,
  organization: null,
  department_position: null,
  direct_report: null,
  indirect_report: null,
  probation_period: null,
  probation_start_date: null,
  probation_end_date: null,
  employee_type: null,
  employee_work_type: null,
  employee_location: null,
  employee_status: null,
  joining_date: null,
  salary: null,
  salary_type: null,
  shift_assignment: null,
  blood_group: null,
  gender: null,
  contract_start_date: null,
  contract_end_date: null,
  active_contract: false,
  confirmation_date: null,
  jd_file: null,
  kpi_file: null,
  branch_id: null,
  onboardingDocuments: [],
  permanent_address: null,
  po_box_number: null,
  nationality:null,
};
const EmployeeProfessionalExperiance = {
  id: null,
  employee_id: null,
  exp_organization: null,
  exp_designation: null,
  exp_discription: null,
  exp_letter: null,
  exp_start_date: null,
  exp_end_date: null,
  disableEndDate: false,
  resume: null,
};
const Employee = {
  id: null,
  personalInformation: EmployeePersonalInformation,
  visaDetails: EmployeeVisaDetails,
  academicRecord: EmployeeAcademicRecord,
  cv: EmployeeCVDetails,
  professionalExperiance: [
    {
      id: null,
      employee_id: null,
      exp_organization: null,
      exp_designation: null,
      exp_discription: null,
      exp_letter: null,
      exp_start_date: null,
      exp_end_date: null,
      disableEndDate: false,
    },
  ],
  department: EmployeeDepartmentInfo,
  bankDetails: EmployeeBankDetails,
  certifications: EmployeeCertifiation,
};

export {
  Employee,
  EmployeePersonalInformation,
  EmployeeVisaDetails,
  EmployeeAcademicRecord,
  EmployeeCVDetails,
  EmployeeProfessionalExperiance,
  EmployeeDepartmentInfo,
  EmployeeBankDetails,
  EmployeeCertifiation,
  EmployeeInformation,
  EmployeeContactInformation,
};
