const Leave = {
  leave_duration: null,
  leave_type: null,
  start_date: null,
  end_date: null,
  full_paid_days: null,
  half_paid_days: null,
  total_days: null,
  reason: null,
  is_full_paid: true,
  status: null,
  reason: null,
  id: null,
  leave_type_name: null,
  leave_duration_name: null,
  employee: null,
  created_at: null,
  request_id: null,
  approval_details: null,
  attachment: null,
  is_cancelled: false,
};

const EmployeeLeaveTypesList = {
  count: 0,
  results: [],
  leaveTypes: 0,
  allotedLeaves: 0,
  remainingLeaves: 0,
  usedLeaves: 0,
};

export const LeaveType = {
  id: null,
  name: null,
  short_code: null,
  leave_count: null,
  is_carry_forward_allowed: null,
  max_carry_forward_limit: null,
  is_encashable: null,
  requires_attachment: null,
  min_days_notice: null,
  nationalities: null,
  branches: null,
  branches_ids: null,
  departments: null,
  departments_ids: null,
  genders: null,
  marital_statuses: null,
  grades: null,
  probation_restriction: null,
  day_count_type: null,
  max_consecutive_days: null,
  is_all_paid: null,
  full_paid_days: null,
  half_paid_days: null,
  status: null,
  tooltip_info: null,
  created_at: null,
  updated_at: null,
};

export const PublicHoliday = {
  name: null,
  date: null,
  end_date: null,
  branches: null,
  country: null,
  religion: null,
  id: null,
};

export const LeaveOffsetSetting = {
  nationalities: null,
  grades: null,
  religions: null,
  branches: null,
  departments: null,
  offset_leave_days: null,
  conversion_ratio_hours: null,
  validity_months: null,
  leave_cap_enabled: false,
  max_leaves_per_month: null,
  max_leaves_per_year: null,
  leave_type: null,
  id:null,
};

export { Leave, EmployeeLeaveTypesList };
