import moment from "moment";
const Leave = {
  leave_duration: null,
  leave_type: null,
  start_date: null,
  end_date: null,
  full_paid_days: null,
  half_paid_days: null,
  total_days: null,
  reason: null,
  is_full_paid: true,

  // employee_id: "",
  // name: "",
  // date: moment(new Date()).format("YYYY-MM-DD"),
  // position: "",
  // department: "",
  // joining_date: "",
  // nationality: "",
  // last_work_day: "",
  // rejoining_date: "",
  // total_leave: "",
  // reason: "",
  // contact_no: "",
  // country_code: "",
  // report_to: "",
  // address_during_leave: "",
};

const EmployeeLeaveTypesList = {
  count: 0,
  results: [],
  leaveTypes: 0,
  allotedLeaves: 0,
  remainingLeaves: 0,
  usedLeaves: 0,
};

export const LeaveType = {
  id: null,
  name: null,
  short_code: null,
  leave_count: null,
  is_carry_forward_allowed: null,
  max_carry_forward_limit: null,
  is_encashable: null,
  requires_attachment: null,
  min_days_notice: null,
  nationalities: null,
  branches: null,
  branches_ids: null,
  departments: null,
  departments_ids: null,
  genders: null,
  marital_statuses: null,
  grades: null,
  probation_restriction: null,
  day_count_type: null,
  max_consecutive_days: null,
  is_all_paid: null,
  full_paid_days: null,
  half_paid_days: null,
  status: null,
  tooltip_info: null,
  created_at: null,
  updated_at: null,
};

export { Leave, EmployeeLeaveTypesList };
