export const PayRun = {
  end_date: null,
  excluded_employees: [],
  gross_amount: null,
  is_payroll_run: null,
  net_amount: null,
  run_date: null,
  start_date: null,
  total_amount: null,
  total_employees: null,
  title: null,
};

export const EmployeePayRoll = {
  basic_salary: null,
  salary_type: null,
  id: null,
  gross_salary: null,
  ctc: null,
  house_allowance: null,
  employee: null,
  hourly_rate: null,
  is_eos_applicable: null,
  is_new: null,
  latest_effective_date: null,
  medical_allowance: null,
  name: null,
  other_allowance: null,
  payout_period: null,
  salary_breakdown_type: null,
  serial_number: null,
  total_deductions: null,
  total_deductions_types: null,
  total_earnings: null,
  total_earnings_types: null,
  total_reimbursements: null,
  transport_allowance: null,
  work_email: null,
};

export const EmployeeSalarySetup = {
  basic_salary: null,
  salary_type: null,
  id: null,
  gross_salary: null,
  ctc: null,
  house_allowance: null,
  employee: null,
  hourly_rate: null,
  is_eos_applicable: null,
  is_new: null,
  medical_allowance: null,
  other_allowance: null,
  transport_allowance: null,
  salary_breakdown_type: "percentage",
  earning_types:[],
  earnings:[],
  deduction_types:[],
  deductions:[],
};
export const EmployeeSalaryRevision = {
  new_salary: null,
  previous_salary: null,
  revision_difference: null,
  percentage: null,
  last_revised_date: null,
  effective_date: null,
  notes: null,
  revision_letter: "DRAFT",
  revision_status: "PENDING",
};
