export const ManpowerPlanning = {
    fiscal_year: null,
    branch: null,
    department: null,
    planned_headcount: null,
    total_allocated_budget: null,
    justification: null,
    id: null,
    existing_headcount: null,
    created_on: null,
    consumed_budget: null,
    consumed_percentage: null,
    consumed_budget_status: null,
}

export const Benefit = {
    id: null,
    created_at: null,
    updated_at: null,
    status: 'active',
    name: null,
    description: null,
    organization: null,
    created_by: null,
    updated_by: null,
}

export const RemoteWorkChecklist = {
    id: null,
    created_at: null,
    updated_at: null,
    status: 'available',
    item_name: null,
    organization: null,
    created_by: null,
    updated_by: null,
}

export const JobType = {
    id: null,
    created_at: null,
    updated_at: null,
    status: 'active',
    name: null,
    description: null,
    organization: null,
    created_by: null,
    updated_by: null,
}

export const Education = {
    id: null,
    created_at: null,
    updated_at: null,
    status: 'active',
    level: null,
    description: null,
    created_by: null,
    updated_by: null,
}

export const CareerLevel = {
    id: null,
    created_at: null,
    updated_at: null,
    status: 'active',
    name: null,
    description: null,
    organization: null,
    created_by: null,
    updated_by: null,
}

export const HeadcountRequest = {
    id: null,
    branch_name: null,
    department_name: null,
    attachment_url: null,
    requested_by_name: null,
    approved_by_name: null,
    approval_details: null,
    allocated_headcount: null,
    consumed_headcount: null,
    remaining_headcount: null,
    requested_headcount: null,
    reason: null,
    attachment: null,
    status: null,
    requested_on: null,
    approved_on: null,
    approved_note: null,
    rejection_reason: null,
    branch: null,
    department: null,
    requested_by: null,
    approved_by: null,
    request: null,

}

export const Requisition = {
    id: null,
    branch_name: null,
    approval_details: null,
    created_at: null,
    updated_at: null,
    job_title: null,
    job_description: null,
    required_skills: null,
    work_mode: 'onsite',
    number_of_positions: null,
    gender_preference: null,
    min_age: null,
    max_age: null,
    experience_min: null,
    experience_max: null,
    salary_min: null,
    salary_max: null,
    justification: null,
    attachment: null,
    recommended_posting_date: null,
    status: null,
    approval_required: true,
    is_draft: null,
    is_emiratization_role: false,
    created_by: null,
    updated_by: null,
    requested_by: null,
    department: null,
    branch: null,
    country: null,
    city: null,
    job_type: null,
    education: null,
    career_level: null,
    request: null,
    remote_work_checklist: null,
    benefits: null,
    enable_benefits: false,
    remote_work_checklist_name: null,
    benefit_names: null,
    job_type_name: null,
    career_level_name: null,
    education_name: null,
}

export const PublishVacancy = {
    id: null,
    job_title: null,
    department: null,
    branch: null,
    total_applications: null,
    created_at: null,
    updated_at: null,
    publish_date: null,
    due_date: null,
    requisition_type: 'both',
    post_on_cohrus: null,
    post_on_linkedin: null,
    post_on_indeed: null,
    post_on_other: null,
    status: null,
    created_by: null,
    updated_by: null,
    requisition: null,
    organization:1,
    posted_portals:1,
}