export const ManpowerPlanning = {
    fiscal_year: null,
    branch: null,
    department: null,
    planned_headcount: null,
    total_allocated_budget: null,
    justification: null,
    id: null,
    existing_headcount: null,
    created_on: null,
    created_by: null,
    consumed_budget: null,
    consumed_percentage: null,
    consumed_budget_status: null,
}

export const Benefit = {
    id: null,
    created_at: null,
    updated_at: null,
    status: 'active',
    name: null,
    description: null,
    created_by: null,
    updated_by: null,
}
export const Skill = {
    id: null,
    name: null,
    description: null,
    created_at: null,
    updated_at: null,
}
export const EmailTemplate = {
    id: null,
    created_by: null,
    name: null,
    subject: null,
    body: null,
    signature: null,
    template_type: null,
    is_active: true,
    created_on: null,
    updated_on: null,
}
export const OfferLetterTemplate = {
    name: null,
    body: null,
    is_active: null,
    id: null,
    created_by: null,
    created_on: null,
    updated_on: null,
}

export const RemoteWorkChecklist = {
    id: null,
    created_at: null,
    updated_at: null,
    status: 'available',
    item_name: null,
    organization: null,
    created_by: null,
    updated_by: null,
}

export const JobType = {
    id: null,
    created_at: null,
    updated_at: null,
    status: 'active',
    name: null,
    description: null,
    organization: null,
    created_by: null,
    updated_by: null,
}

export const Education = {
    id: null,
    created_at: null,
    updated_at: null,
    status: 'active',
    level: null,
    description: null,
    created_by: null,
    updated_by: null,
}

export const CareerLevel = {
    id: null,
    created_at: null,
    updated_at: null,
    status: 'active',
    name: null,
    description: null,
    organization: null,
    created_by: null,
    updated_by: null,
}

export const InterviewType = {
    id: null,
    created_at: null,
    updated_at: null,
    is_active: true,
    name: null,
    description: null,
    created_by: null,
    updated_by: null,
    created_by_name: null,
    updated_by_name: null,
}

export const FeedBackForm = {
    id: null,
    name: null,
    status: 'ACTIVE',
    created_by: null,
    created_on: null,
    sections: [{
        id: null,
        title: null,
        fields: [{
            id: null,
            label: null,
            field_type: null,
            rating_scale_max: null,
            radio_options: null,
        }],
    }]
}

export const HeadcountRequest = {
    id: null,
    branch_name: null,
    department_name: null,
    attachment_url: null,
    requested_by_name: null,
    approved_by_name: null,
    approval_details: null,
    allocated_headcount: null,
    consumed_headcount: null,
    remaining_headcount: null,
    requested_headcount: null,
    reason: null,
    attachment: null,
    status: null,
    requested_on: null,
    approved_on: null,
    approved_note: null,
    rejection_reason: null,
    branch: null,
    department: null,
    requested_by: null,
    approved_by: null,
    request: null,
}

export const Requisition = {
    id: null,
    branch_name: null,
    approval_details: null,
    created_at: null,
    updated_at: null,
    job_title: null,
    job_description: null,
    required_skillset: null,
    required_skillset_name: null,
    work_mode: 'onsite',
    number_of_positions: null,
    gender_preference: null,
    min_age: null,
    max_age: null,
    experience_min: null,
    experience_max: null,
    salary_min: null,
    salary_max: null,
    justification: null,
    attachment: null,
    recommended_posting_date: null,
    status: null,
    approval_required: true,
    is_draft: null,
    is_emiratization_role: false,
    created_by: null,
    updated_by: null,
    requested_by: null,
    department: null,
    branch: null,
    country: null,
    city: null,
    job_type: null,
    education: null,
    career_level: null,
    request: null,
    remote_work_checklist: null,
    benefits: null,
    enable_benefits: false,
    remote_work_checklist_name: null,
    benefit_names: null,
    job_type_name: null,
    career_level_name: null,
    education_name: null,
}

export const PublishVacancy = {
    id: null,
    job_title: null,
    department: null,
    branch: null,
    total_applications: null,
    created_at: null,
    updated_at: null,
    publish_date: null,
    due_date: null,
    requisition_type: 'both',
    post_on_cohrus: null,
    post_on_linkedin: null,
    post_on_indeed: null,
    post_on_other: null,
    status: null,
    created_by: null,
    updated_by: null,
    requisition: null,
    organization: 1,
    posted_portals: null,
}

export const Applicants = {
    id: null,
    published_vacancy: null,
    candidate_id: null,
    candidate_name: null,
    email: null,
    contact_number: null,
    application_source: null,
    emiratization_flag: null,
    status: null,
    attachments: null,
    created_by: null,
    rejection_reason: null,
    application_date: null,
    location: null,
    job_title: null,
    blacklist: null,
    recruitment_shortlist: null,
    interviews: null,
    recruitment_rejected: null,
    screened_by: null,
    screened_date: null,
    vacancy_department: null,
    resume: null,
    ai_match_score: null,
    ai_matched_skills: null,
    ai_missing_skills: null,
    ai_suggested: null,

}

export const RejectedApplication = {
    id: null,
    applicant: null,
    rejection_reason: null,
    remarks: null,
    rejected_by: null,
    rejected_on: null,
}
export const ResumeBankApplication = {
    id: null,
    applicant: null,
    candidate_name: null,
    email: null,
    contact_number: null,
    job_title_applied_for: null,
    application_date: null,
    resume: null,
    recommended_department: null,
    recommended_designation: null,
    added_on: null,
    added_by: null,
    application_source:null,
}

export const Interview = {
    id: null,
    applicant: null,
    interview_type: null,
    interview_type_name: null,
    scheduled_datetime: null,
    panel: null,
    panel_name: null,
    email_template: null,
    generate_meeting_link: null,
    require_demographics: null,
    created_by: null,
    created_at: null,
    status: null,
    job_title: null,
    candidate_name: null,
    candidate_id: null,
    contact_number: null,
    email: null,
    ai_match_score: null,
    ai_matched_skills: null,
    ai_missing_skills: null,
    ai_suggested: null,
}

export const InterviewFeedback = {
    interview: null,
    panel_member: null,
    panel_member_name: null,
    feedback_form: null,
    rating: null,
    comments: null,
    is_submitted: null,
    recommendation: null,
    id: null,
    responses: null,
}

export const ShortlistedApplicant = {
    id: null,
    applicant: null,
    desired_salary: null,
    expected_joining_date: null,
    remarks: null,
    shortlisted_by: null,
    shortlisted_on: null,
}


export const BlacklistApplicant = {
    id: null,
    applicant: null,
    reasons: null,
    reason_ids: null,
    remarks: null,
    blacklisted_by: null,
    blacklisted_on: null,
    removed_by: null,
    removed_on: null,
}


export const BlacklistReason = {
    id: null,
    name: null,
    description: null,
    is_active: null,
    created_at: null,
    created_by: null,
    remove: null,
}

export const OfferLetter = {
    offered_salary: null,
    expected_joining_date: null,
    designation: null,
    reporting_manager: null,
    work_location: null,
    remarks: null,
    generated_on: null,
    final_letter_body: null,
    applicant: null,
    template: null,
    generated_by: null,
    approved_by: null,
    rejected_by: null,
    last_updated_by: null,
    request: null,
    id: null,
    approved_on: null,
    rejected_on: null,
    rejection_remarks: null,
    last_updated_on: null,
    status: null,
    approval_details: null,
    final_letter_pdf: null,
}

export const OfferTracking = {
    id: null,
    applicant: null,
    applicant_name: null,
    offer_letter_id: null,
    status: null,
    validity_date: null,
    joining_date: null,
    sent_by: null,
    sent_on: null,
    updated_by: null,
    updated_on: null,
    audit_logs: null,
    offer_letter: null,
}