export const EmployeeTransfer = {
  new_branch: null,
  effective_transfer_date: null,
  reason_of_transfer: null,
  notes: null,
  status: "PENDING",
  transfer_type: "INTERNAL",
  employee_id: null,
  new_department: null,
  new_reporting_manager: null,
  reason_of_rejection: null,
  old_department: null,
  old_branch: null,
  reporting_manager: null,
  hr_manager: null,
  initiated_by: null,
  approval_details: null,
  created_at:null,
};

export const JobRotation = {
  rotation_type: "temporary",
  rotation_expiry_date: null,
  rotation_cap_time: null,
  effective_date: null,
  custom_reason: null,
  notes: null,
  status: null,
  employee: null,
  new_branch: null,
  new_department: null,
  reason: null,
  created_by: null,
  new_designation: null,
  new_reporting_manager: null,
  created_at: null,
  old_department: null,
  old_designation: null,
  old_branch: null,
  old_reporting_manager: null,
  approval_details: null,
  hierarchy_request:null,
}


