import {
  PayrollDashboard,
  PayrollRunWizard,
  PayrollSetupConfiguration,
  EarningsDeductionsConfig,
  TaxManagement,
  CountryCurrencyManagement,
  WPSPaymentGeneration,
  ClaimsReimbursements,
  AIRecommendations,
  PayrollReports,
  PayrollAuditLogs,
  PayrollPoliciesSettings,
  CountryCurrencySettings,
  StatutoryRulesSettings,
  EarningsDeductionsSettings,
  CostCentersMappingSettings,
  HolidayCalendarSettings,
  EmployeeDataIntegrationLanding,
  EmployeeMasterSyncSettings,
  SalaryComponentsFetchSettings,
  AttendanceLinksSettings,
  EmployeeTypeSettings,
  BulkUploadMappingSettings,
  EarningHeadsSettings,
  DeductionHeadsSettings,
  CustomRulesSettings,
  OvertimeCalculationSettings,
  StatutoryContributionsSettings,
  OneTimePaymentsSettings,
  PayrollProcessingWizard,
  PeriodSelection,
  PayrollComputation,
  EmployeeInclusion,
  PayrollWorkflow,
  ErrorValidation,
  PayrollPreview,
  TaxCalculation,
  PFSocialSecurity,
  GratuityCalculation,
  ContributionBreakdown,
  TaxTablesUpdate,
  GovernmentReporting,
  ExchangeRateConversion,
  CurrencyDisplay,
  CountryRules,
  LedgerMapping,
  ConsolidatedDashboard,
  UAESIFGeneration,
  UKBankFormats,
  AfricaBankFormats,
  PaymentBatchApprovals,
  PayrollAlerts,
  BankAPIIntegration,
  AutoGeneratedPayslips,
  PDFPayslips,
  EmployeePortalAccess,
  PayrollHistory,
  YearEndStatements,
  ManualOverride,
  RetroactiveCorrections,
  OffCyclePayroll,
  LeaveAdjustments,
  LoansAdvances,
  AnomalyDetection,
  SalaryForecast,
  ComplianceDetection,
  SmartReminders,
  AIChatbot,
  PayrollSummary,
  CostCenterAnalysis,
  StatutoryReports,
  ForecastReports,
  ExportTools,
  BIIntegration,
  RoleBasedAccess,
  AuditTrail,
  ChangeHistory,
  ComplianceChecks,
  DataEncryption,
  AttendanceShiftManagement,
  LeaveTimeoffModule,
  LoanReimbursementModule,
  GeneralLedgerERPSystems,
  BankPaymentAPIs,
  TaxAuthorityWPSSubmission,
} from "app/modules/GlobalPayroll";

/**
 * Global Payroll Module Routes
 * These routes will be added to the main SidebarRoutes array
 */

const GlobalPayrollRoutes = [
  // Main Payroll Dashboard
  {
    path: "/payroll/global",
    component: <PayrollDashboard />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Payroll Run Wizard
  {
    path: "/payroll/run/create",
    component: <PayrollRunWizard />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Payroll Setup & Configuration
  {
    path: "/payroll/setup-configuration",
    component: <PayrollSetupConfiguration />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Configuration Routes
  {
    path: "/payroll/configuration/earnings-deductions",
    component: <EarningsDeductionsConfig />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/configuration/tax-management",
    component: <TaxManagement />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/configuration/country-currency",
    component: <CountryCurrencyManagement />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // WPS & Payments
  {
    path: "/payroll/wps/generate",
    component: <WPSPaymentGeneration />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Claims & Reimbursements
  {
    path: "/payroll/claims",
    component: <ClaimsReimbursements />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // AI Recommendations
  {
    path: "/payroll/ai-recommendations",
    component: <AIRecommendations />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Reports & Analytics
  {
    path: "/payroll/reports",
    component: <PayrollReports />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Audit Logs
  {
    path: "/payroll/audit-logs",
    component: <PayrollAuditLogs />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Payroll Settings Pages
  {
    path: "/payroll/settings/policies",
    component: <PayrollPoliciesSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/settings/country-currency",
    component: <CountryCurrencySettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/settings/statutory-rules",
    component: <StatutoryRulesSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/settings/earnings-deductions",
    component: <EarningsDeductionsSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/settings/cost-centers",
    component: <CostCentersMappingSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/settings/holiday-calendar",
    component: <HolidayCalendarSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Employee Data Integration Landing Page
  {
    path: "/payroll/employee-data-integration",
    component: <EmployeeDataIntegrationLanding />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Employee Data Integration Pages
  {
    path: "/payroll/integration/master-sync",
    component: <EmployeeMasterSyncSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/integration/salary-components",
    component: <SalaryComponentsFetchSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/integration/attendance-links",
    component: <AttendanceLinksSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/integration/employee-types",
    component: <EmployeeTypeSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/integration/bulk-upload",
    component: <BulkUploadMappingSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Earnings & Deductions Pages
  {
    path: "/payroll/earnings-deductions",
    component: <EarningHeadsSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/earnings/earning-heads",
    component: <EarningHeadsSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/earnings/deduction-heads",
    component: <DeductionHeadsSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/earnings/custom-rules",
    component: <CustomRulesSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/earnings/overtime-calculation",
    component: <OvertimeCalculationSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/earnings/statutory-contributions",
    component: <StatutoryContributionsSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/earnings/one-time-payments",
    component: <OneTimePaymentsSettings />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Payroll Run & Processing Landing Page
  {
    path: "/payroll/run-processing",
    component: <PayrollProcessingWizard />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Payroll Run & Processing Pages
  {
    path: "/payroll/run/processing-wizard",
    component: <PayrollProcessingWizard />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/run/period-selection",
    component: <PeriodSelection />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/run/computation",
    component: <PayrollComputation />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/run/employee-inclusion",
    component: <EmployeeInclusion />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/run/workflow",
    component: <PayrollWorkflow />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/run/validation",
    component: <ErrorValidation />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/run/preview",
    component: <PayrollPreview />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Tax, PF & Statutory Compliance Landing Page
  {
    path: "/payroll/tax-compliance",
    component: <TaxCalculation />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Tax, PF & Statutory Compliance Pages
  {
    path: "/payroll/compliance/tax-calculation",
    component: <TaxCalculation />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/compliance/pf-social-security",
    component: <PFSocialSecurity />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/compliance/gratuity",
    component: <GratuityCalculation />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/compliance/contribution-breakdown",
    component: <ContributionBreakdown />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/compliance/tax-tables",
    component: <TaxTablesUpdate />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/compliance/government-reporting",
    component: <GovernmentReporting />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Multi-Currency & Multi-Country Landing Page
  {
    path: "/payroll/multi-currency",
    component: <ConsolidatedDashboard />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Multi-Currency & Multi-Country Pages
  {
    path: "/payroll/currency/exchange-rates",
    component: <ExchangeRateConversion />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/currency/currency-display",
    component: <CurrencyDisplay />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/currency/country-rules",
    component: <CountryRules />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/currency/ledger-mapping",
    component: <LedgerMapping />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/currency/consolidated-dashboard",
    component: <ConsolidatedDashboard />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // WPS & Payment Processing Landing Page
  {
    path: "/payroll/wps-payment",
    component: <UAESIFGeneration />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // WPS & Payment Processing Pages
  {
    path: "/payroll/wps/uae-sif-generation",
    component: <UAESIFGeneration />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/wps/uk-bank-formats",
    component: <UKBankFormats />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/wps/africa-bank-formats",
    component: <AfricaBankFormats />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/wps/payment-batch-approvals",
    component: <PaymentBatchApprovals />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/wps/payroll-alerts",
    component: <PayrollAlerts />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/wps/bank-api-integration",
    component: <BankAPIIntegration />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Payslip & Employee Self Service Landing Page
  {
    path: "/payroll/payslip-self-service",
    component: <AutoGeneratedPayslips />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Payslip & Employee Self Service Pages
  {
    path: "/payroll/payslip/auto-generated",
    component: <AutoGeneratedPayslips />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/payslip/pdf-download",
    component: <PDFPayslips />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/payslip/employee-portal",
    component: <EmployeePortalAccess />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/payslip/payroll-history",
    component: <PayrollHistory />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/payslip/year-end-statements",
    component: <YearEndStatements />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Adjustments & Corrections Landing Page
  {
    path: "/payroll/adjustments-corrections",
    component: <ManualOverride />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Adjustments & Corrections Pages
  {
    path: "/payroll/adjustments/manual-override",
    component: <ManualOverride />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/adjustments/retroactive-corrections",
    component: <RetroactiveCorrections />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/adjustments/off-cycle-payroll",
    component: <OffCyclePayroll />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/adjustments/leave-adjustments",
    component: <LeaveAdjustments />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/adjustments/loans-advances",
    component: <LoansAdvances />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // AI & Automation Features Landing Page
  {
    path: "/payroll/ai-automation",
    component: <AnomalyDetection />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // AI & Automation Features Pages
  {
    path: "/payroll/ai/anomaly-detection",
    component: <AnomalyDetection />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/ai/salary-forecast",
    component: <SalaryForecast />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/ai/compliance-detection",
    component: <ComplianceDetection />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/ai/smart-reminders",
    component: <SmartReminders />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/ai/chatbot",
    component: <AIChatbot />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Reporting & Analytics Landing Page
  {
    path: "/payroll/reporting-analytics",
    component: <PayrollSummary />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Reporting & Analytics Pages
  {
    path: "/payroll/reports/payroll-summary",
    component: <PayrollSummary />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/reports/cost-center-analysis",
    component: <CostCenterAnalysis />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/reports/statutory-reports",
    component: <StatutoryReports />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/reports/forecast-reports",
    component: <ForecastReports />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/reports/export-tools",
    component: <ExportTools />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/reports/bi-integration",
    component: <BIIntegration />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Security & Access Control Landing Page
  {
    path: "/payroll/security-access",
    component: <RoleBasedAccess />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Security & Access Control Pages
  {
    path: "/payroll/security/role-based-access",
    component: <RoleBasedAccess />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/security/audit-trail",
    component: <AuditTrail />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/security/change-history",
    component: <ChangeHistory />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/security/compliance-checks",
    component: <ComplianceChecks />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/security/data-encryption",
    component: <DataEncryption />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Integration Points Landing Page
  {
    path: "/payroll/integration-points",
    component: <AttendanceShiftManagement />,
    name: "EMPLOYEES_PAYROLL",
  },
  
  // Integration Points Pages
  {
    path: "/payroll/integration/attendance-shift",
    component: <AttendanceShiftManagement />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/integration/leave-timeoff",
    component: <LeaveTimeoffModule />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/integration/loan-reimbursement",
    component: <LoanReimbursementModule />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/integration/general-ledger",
    component: <GeneralLedgerERPSystems />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/integration/bank-payment",
    component: <BankPaymentAPIs />,
    name: "EMPLOYEES_PAYROLL",
  },
  {
    path: "/payroll/integration/tax-wps",
    component: <TaxAuthorityWPSSubmission />,
    name: "EMPLOYEES_PAYROLL",
  },
];

// Export for integration with main routes
export { GlobalPayrollRoutes };

