const ModuleListByUserRole = [
  {
    moduleId: 1,
    moduleName: "Dashboard",
    parentModuleId: null,
    userRole: [],
  },
  {
    moduleId: 2,
    moduleName: "Create Profile",
    parentModuleId: null,
    userRole: [],
  },
  {
    moduleId: 3,
    moduleName: "Team Management",
    parentModuleId: null,
    userRole: [1,2,3],
  },
  {
    moduleId: 4,
    moduleName: "Profile Management",
    parentModuleId: 3,
    userRole: [1,2,3],
  },
  {
    moduleId: 5,
    moduleName: "Profile Settings",
    parentModuleId: 3,
    userRole: [1,2,3],
  },
  {
    moduleId: 6,
    moduleName: "Travel Details",
    parentModuleId: 3,
    userRole: [1,2,3],
  },
  {
    moduleId: 7,
    moduleName: "Exit & Clearance",
    parentModuleId: 3,
    userRole: [1,2,3],
  },
  {
    moduleId: 8,
    moduleName: "Customize Employee",
    parentModuleId: 3,
    userRole: [1,2,3],
  },
  {
    moduleId: 9,
    moduleName: "Relocation",
    parentModuleId: 3,
    userRole: [1,2,3],
  },
  {
    moduleId: 10,
    moduleName: "Internal",
    parentModuleId: 3,
    userRole: [1,2,3],
  },
  {
    moduleId: 11,
    moduleName: "External",
    parentModuleId: 3,
    userRole: [1,2,3],
  },
  {
    moduleId: 12,
    moduleName: "Self Service Hub",
    parentModuleId: null,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 13,
    moduleName: "My Profile",
    parentModuleId: 12,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 14,
    moduleName: "My Team",
    parentModuleId: 12,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 15,
    moduleName: "Calendar",
    parentModuleId: 12,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 16,
    moduleName: "My Payroll",
    parentModuleId: 12,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 17,
    moduleName: "My Claims",
    parentModuleId: 12,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 18,
    moduleName: "Exit",
    parentModuleId: 12,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 19,
    moduleName: "My Travel Details",
    parentModuleId: 12,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 20,
    moduleName: "Payroll",
    parentModuleId: null,
    userRole: [1,2,3],
  },
  {
    moduleId: 21,
    moduleName: "Employee Payrolls",
    parentModuleId: 20,
    userRole: [1,2,3],
  },
  {
    moduleId: 22,
    moduleName: "Salary Setup",
    parentModuleId: 20,
    userRole: [1,2,3],
  },
  {
    moduleId: 23,
    moduleName: "Claim Request",
    parentModuleId: 20,
    userRole: [1,2,3],
  },
  {
    moduleId: 24,
    moduleName: "Pay Run",
    parentModuleId: 20,
    userRole: [1,2,3],
  },
  {
    moduleId: 25,
    moduleName: "Loans",
    parentModuleId: 20,
    userRole: [1,2,3],
  },
  {
    moduleId: 26,
    moduleName: "Payslips",
    parentModuleId: 20,
    userRole: [1,2,3],
  },
  {
    moduleId: 27,
    moduleName: "Task Management",
    parentModuleId: null,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 28,
    moduleName: "My Task",
    parentModuleId: 27,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 29,
    moduleName: "My Team DTR",
    parentModuleId: 27,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 30,
    moduleName: "Project Board",
    parentModuleId: 27,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 31,
    moduleName: "Time Management",
    parentModuleId: 27,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 32,
    moduleName: "Leave Tracker",
    parentModuleId: null,
    userRole: [1,2,3],
  },
  {
    moduleId: 33,
    moduleName: "Leave Records",
    parentModuleId: 32,
    userRole: [1,2,3],
  },
  {
    moduleId: 34,
    moduleName: "Leave Request",
    parentModuleId: 32,
    userRole: [1,2,3],
  },
  {
    moduleId: 35,
    moduleName: "Talent Sphere",
    parentModuleId: null,
    userRole: [1,3],
  },
  {
    moduleId: 36,
    moduleName: "Personnel Requisition",
    parentModuleId: 35,
    userRole: [1,3],
  },
  {
    moduleId: 37,
    moduleName: "Jobs",
    parentModuleId: 35,
    userRole: [1,3],
  },
  {
    moduleId: 38,
    moduleName: "Applicants",
    parentModuleId: 35,
    userRole: [1,3],
  },
  {
    moduleId: 39,
    moduleName: "Referrals",
    parentModuleId: 35,
    userRole: [1,3],
  },
  {
    moduleId: 40,
    moduleName: "On Boarding",
    parentModuleId: 35,
    userRole: [1,3],
  },
  {
    moduleId: 41,
    moduleName: "Daily Task Report",
    parentModuleId: null,
    userRole: [1,2,3],
  },
  {
    moduleId: 42,
    moduleName: "My DTR",
    parentModuleId: 41,
    userRole: [1,2,3],
  },
  {
    moduleId: 43,
    moduleName: "Create Task",
    parentModuleId: 41,
    userRole: [1,2,3],
  },
  {
    moduleId: 44,
    moduleName: "Personal Development",
    parentModuleId: null,
    userRole: [1,2,3],
  },
  {
    moduleId: 45,
    moduleName: "Learn",
    parentModuleId: 44,
    userRole: [1,2,3],
  },
  {
    moduleId: 46,
    moduleName: "Career Planning",
    parentModuleId: 44,
    userRole: [1,2,3],
  },
  {
    moduleId: 47,
    moduleName: "Succession Plan",
    parentModuleId: 44,
    userRole: [1,2,3],
  },
  {
    moduleId: 48,
    moduleName: "Attendance",
    parentModuleId: null,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 49,
    moduleName: "People Engagement",
    parentModuleId: null,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 50,
    moduleName: "Announcement",
    parentModuleId: 49,
    userRole: [1,2,3,4],
  },
  {
    moduleId: 51,
    moduleName: "Performance Management",
    parentModuleId: null,
    userRole: [1,2,3],
  },
  {
    moduleId: 54,
    moduleName: "Employee Evaluation",
    parentModuleId: 51,
    userRole: [1,2,3],
  },
  {
    moduleId: 52,
    moduleName: "Reports",
    parentModuleId: null,
    userRole: [1,2],
  },
  {
    moduleId: 53,
    moduleName: "Recognition",
    parentModuleId: 49,
    userRole: [1,2,3,4],
  },
];

export { ModuleListByUserRole };
