// ✅ Tab configuration (static, no hook calls here!)
import {
    Benefits,
    AddUpdateBenefitForm,
    OfferLetterTemplates,
    AddUpdateOfferLetterTemplateForm,
    FeedBackForms,
    AddUpdateFeedBackForm,
    InterviewTypes,
    AddUpdateInterviewTypeForm,
    CareerLevels,
    AddUpdateCareerLevelForm,
    Educations,
    AddUpdateEducationForm,
    JobTypes,
    AddUpdateJobTypeForm,
    RemoteWorkChecklist,
    AddUpdateRemoteWorkChecklistForm,
    EmailTemplates,
    AddUpdateEmailTemplateForm,
} from "app/modules/TalentSphere/SettingManagement";
import Demographics from "app/modules/TalentSphere/DemographicsForm";

// 🔹 Central config for all tabs
export const SETTING_TAB_CONFIG = [
    {
        key: "benefits",
        label: "Benefits",
        viewPerm: "VIEW_TS_BENEFITS",
        addPerm: "ADD_TS_BENEFITS",
        list: (reload) => <Benefits reload={reload} />,
        form: AddUpdateBenefitForm,
    },
    {
        key: "feedback-form",
        label: "Feedback Forms",
        viewPerm: "VIEW_TS_BENEFITS",
        addPerm: "ADD_TS_BENEFITS",
        list: (reload) => <FeedBackForms reload={reload} />,
        form: AddUpdateFeedBackForm,
    },
    {
        key: "interview-type",
        label: "Interview Types",
        viewPerm: "ADD_TS_BENEFITS",
        addPerm: "ADD_TS_BENEFITS",
        list: (reload) => <InterviewTypes reload={reload} />,
        form: AddUpdateInterviewTypeForm,
    },
    {
        key: "career-level",
        label: "Career Level",
        viewPerm: "VIEW_TS_CAREER_LEVEL",
        addPerm: "ADD_TS_CAREER_LEVEL",
        list: (reload) => <CareerLevels reload={reload} />,
        form: AddUpdateCareerLevelForm,
    },
    {
        key: "education",
        label: "Education",
        viewPerm: "VIEW_TS_EDUCATION",
        addPerm: "ADD_TS_EDUCATION",
        list: (reload) => <Educations reload={reload} />,
        form: AddUpdateEducationForm,
    },
    {
        key: "job-type",
        label: "Job Types",
        viewPerm: "VIEW_TS_JOB_TYPE",
        addPerm: "ADD_TS_JOB_TYPE",
        list: (reload) => <JobTypes reload={reload} />,
        form: AddUpdateJobTypeForm,
    },
    {
        key: "checklist",
        label: "Remote Work Checklist",
        viewPerm: "VIEW_TS_REMOTE_WORK_CHECKLIST",
        addPerm: "ADD_TS_REMOTE_WORK_CHECKLIST",
        list: (reload) => <RemoteWorkChecklist reload={reload} />,
        form: AddUpdateRemoteWorkChecklistForm,
    },
    {
        key: "add-demographics",
        label: "Add Demographics",
        // no permissions required
        list: () => <Demographics />,
        form: null,
    },
    {
        key: "email-template",
        label: "Email Templates",
        // viewPerm: "VIEW_TS_BENEFITS",
        addPerm: "ADD_TS_BENEFITS",
        list: (reload) => <EmailTemplates reload={reload} />,
        form: AddUpdateEmailTemplateForm,
    },
       {
        key: "offer-letter-template",
        label: "Offer Letter Templates",
        viewPerm: "VIEW_TS_BENEFITS",
        addPerm: "ADD_TS_BENEFITS",
        list: (reload) => <OfferLetterTemplates reload={reload} />,
        form: AddUpdateOfferLetterTemplateForm,
    },
];