import React from "react";
import { StatusLabel } from "components";
import ClearanceCertificateActions from "./ClearanceCertificateActions";
import { EmployeeID } from "utils/getValuesFromTables";
import { renderDate } from "utils/renderValues";
import { Badge } from "components/ui/badge";
import { EmployeeUsername } from "utils/getValuesFromTables";

export const ClearanceCertificatesColumns = (
  reload,
  certificatesList = [],
  clearanceTypes = []
) => [
  {
    dataField: "employee_name",
    text: "Employee Name",
    sort: true,
    formatter: (cell, row) => {
      return cell || "N/A";
    },
  },
  {
    dataField: "id", // Using certificate ID for employee ID display
    text: "Employee ID",
    sort: true,
    formatter: (cell, row) => {
      // You might need to get employee ID from request relationship
      return row.request || cell || "N/A";
    },
  },
  {
    dataField: "department",
    text: "Department",
    sort: true,
    formatter: (cell, row) => {
      return cell || "N/A";
    },
  },
  {
    dataField: "last_working_day",
    text: "Last Working Day",
    sort: true,
    formatter: (cell) => renderDate(cell),
  },
  {
    dataField: "status",
    text: "Certificate Status",
    sort: true,
    formatter: (cell) => {
      const statusMap = {
        PENDING: { label: "Pending", variant: "warning" },
        GENERATED: { label: "Generated", variant: "info" },
        SENT: { label: "Sent", variant: "success" },
      };

      const status = statusMap[cell] || {
        label: cell || "Unknown",
        variant: "neutral",
      };

      return (
        <StatusLabel status={status.label} variant={status.variant}>
          {status.label}
        </StatusLabel>
      );
    },
  },
  {
    dataField: "generated_on",
    text: "Certificate Generated On",
    sort: true,
    formatter: (cell) => renderDate(cell, "--", "date-time"),
  },
  {
    dataField: "generated_by",
    text: "Certificate Generated By",
    sort: true,
    formatter: (cell) => (
      <EmployeeUsername value={cell} fallBackText="System" />
    ),
  },
  {
    dataField: "sent_to_employee",
    text: "Sent to Employee",
    sort: true,
    formatter: (cell) => (
      <Badge variant={cell ? "success" : "secondary"}>
        {cell ? "Yes" : "No"}
      </Badge>
    ),
  },
  {
    dataField: "clearance_type",
    text: "Clearance Type",
    sort: true,
    formatter: (cell, row) => {
      // Find clearance type name from clearanceTypes array
      if (!Array.isArray(clearanceTypes) || clearanceTypes.length === 0) {
        return cell || "N/A";
      }

      const clearanceType = clearanceTypes.find((type) => type?.id === cell);
      return clearanceType?.name || cell || "N/A";
    },
  },
  {
    dataField: "actions",
    text: "Actions",
    isDummyField: true,
    csvExport: false,
    formatter: (cell, row) => (
      <ClearanceCertificateActions
        data={row}
        reloadData={reload}
        clearanceTypes={clearanceTypes}
      />
    ),
    style: {
      textAlign: "center",
    },
  },
];
