import React, { useState } from "react";
import {
    NavigationSheetComponent,
    DetailContent,
    StatusList,
} from "components";
import { FormatID } from "utils/getValuesFromTables";
import { renderDate } from "utils/renderValues";
import { StatusLabel, StatusButtons } from "components";
import { getOfferLetterData, saveUpdateOfferLetter } from "app/hooks/talentSphere";
import { SentOfferForm, AddUpdateManpower } from "app/modules/TalentSphere";
import { EmployeeName } from "utils/getValuesFromTables";
import AttachmentUI from "components/ui/AttachmentUI";
import { Button } from "components/ui/button";
import { usePermissions } from "utils/PermissionUtils";
import { errorClassName } from "components/FormControl";

const ViewOfferGenerated = ({
    isOpen,
    setIsOpen,
    currentId,
    reloadData = () => { },
    DataList = [],
    ViewMode = false,
    isTeamView = false,

}) => {
    const { hasAccess } = usePermissions();
    const sendOfferPermitted = hasAccess("SEND_OFFER_TO_APPLICANTS");
    const updateBudgetPermitted = hasAccess("EDIT_MANPOWER");
    const [forceLoad, setForceLoad] = useState(false);
    const [FormData, setFormData] = useState({});
    const [OpenSentOfferForm, setOpenSentOfferForm] = useState(false);
    const [OpenManpowerForm, setOpenManpowerForm] = useState(false);
    const handleSubmit = async (id, { comment }) => {
        try {
            await saveUpdateOfferLetter({ rejection_remarks: comment }, id);
        } catch (error) {
            // Handle errors and rollback form data
            console.error(error);
        }
    };

    const handleSentApplicant = (event, data) => {
        event.preventDefault();
        event.stopPropagation();
        setFormData({ applicant: data.applicant, offer_letter: data.id })
        setOpenSentOfferForm(true);
    }
    const handleUpdateBudget = (event,data) => {
        debugger
        event.preventDefault();
        event.stopPropagation();
        setFormData({ department: data.requisitation_department, branch: data.requisitation_branch })
        setOpenManpowerForm(true);
    }
    // Define the fields to display
    const fields = [
        {
            customContent: true,
            renderContent: (data) => {
                return (
                    <div className="flex flex-wrap justify-end gap-2 items-center flex-wrap">
                        <StatusLabel className="ml-10" status={data.status}>
                            {data?.status?.toLowerCase()}
                        </StatusLabel>
                    </div>
                );
            },
        },
        {
            title: "Applicant Details",

            field: [
                {
                    key: "applicant",
                    label: "Applicant Id",
                    formatter: (cell, row) => <FormatID value={cell} prefix={"APP-"} />,
                },
                {
                    key: "candidate_name",
                    label: "Applicant Name",
                },
                {
                    key: "candidate_email",
                    label: "Email",
                },

                {
                    key: "candidate_contact",
                    label: "Contact Number",
                },
                {
                    key: "designation",
                    label: "Job Title",
                },
            ],
        },
        {
            title: "Offer Details",
            footerTitle: "Generated On",
            footerField: "generated_on",
            field: [
                {
                    key: "generated_by",
                    label: "Generated By",
                    formatter: (cell) => <EmployeeName value={cell} />
                },
                {
                    key: "offered_salary",
                    label: "Offered Salary",
                },
                {
                    key: "expected_joining_date",
                    label: "Joining Date",
                    formatter: (cell) => renderDate(cell),
                },
                {
                    key: "designation",
                    label: "Designation",
                },
                {
                    key: "work_location",
                    label: "Work Location",
                },
                {
                    key: "rejection_remarks",
                    label: "Rejection Reason",
                    renderCondition: (cell) => Boolean(cell),
                },
            ],
        },
        {
            title: `Offer Letter`,
            field: [
                {
                    key: 'final_letter_pdf',
                    formatter: (cell, data) =>
                        cell ? (
                            <AttachmentUI
                                attachment={cell}
                                name={`Final Offer Letter`}
                                viewOnly={true}
                            />
                        ) : (
                            <div className="text-neutral-1000 text-sm">No document attached</div>
                        ),
                },
            ],
        },
        {
            title: "AI-Based Offer Letter Consistency",
            field: [
                {
                    key: "ai_budget_status",
                    label: "Budget Validation",
                    formatter: (cell) => <StatusLabel status={cell}>
                        {cell?.toLowerCase()}
                    </StatusLabel>
                },
                {
                    key: "ai_confidence_score",
                    label: "AI Confidence Score",
                },
                {
                    key: "ai_salary_match_status",
                    label: "Salary vs Job Grade",
                },

                {
                    key: "ai_missing_fields",
                    label: "Missing Data",
                },
            ],
        },
        {
            title: "Approval Details",
            field: [
                {
                    key: "approval_details",
                    formatter: (cell) => (
                        <StatusList status_list={cell} className="my-3" />
                    ),
                },
            ],
        },
        {
            customContent: true,
            renderContent: (data) => {
                if (ViewMode || isTeamView) return null;
                if (data.status?.toLowerCase() === 'pending') {
                    if (data.ai_budget_status !== "Within Budget") {
                        return (
                            <>
                                <div className={`${errorClassName} ml-3 mt-2`}>The offered salary exceeds the allocated budget for this department. Please update the budget before proceeding</div>
                                {updateBudgetPermitted && <Button className="flex justify-end mt-4" onClick={(event) => handleUpdateBudget(event, data)}>Update Budget</Button>}
                            </>
                        );
                    } if (data.ai_missing_fields !== 'All Required Fields Present') return <div className={`${errorClassName} ml-3 mt-2`}>The offered letter is missing with some required informations</div>;
                }
                if (data?.status?.toLowerCase() === 'approved') {
                    if (sendOfferPermitted)
                        return <Button className="flex justify-end mt-4" onClick={(event) => handleSentApplicant(event, data)}>Send to Applicant</Button>
                }
                else return (
                    <>
                        {data.ai_salary_match_status === 'Out of Range' &&
                            <div className='text-amber-500 text-sm'>Offered salary is outside the recommended range for this job grade</div>
                        }
                        <StatusButtons
                            permissionKey={'MANAGE_APPLICANT_OFFER_LETTER'}
                            status={data?.status}
                            current_approver={data.current_approver}
                            final_approver={data.final_approvers || []}
                            request_id={data.request}
                            RejectionConfig={{ label: 'Rejection Reason', required: true, }}
                            setResponse={async (response, status, approval_data) => {
                                if (response) {
                                    if (status?.toLowerCase() === 'rejected') {
                                        await handleSubmit(data.id, approval_data);
                                    }
                                    setForceLoad(!forceLoad);
                                }
                            }}
                        />
                    </>
                );
            },
        },
    ];

    const fetchData = async (id, isMounted) => {
        try {
            const response = await getOfferLetterData(id);
            if (isMounted) {
                return response;
            }
        } catch (error) {
            console.error("Error fetching roles:", error);
        }
    };

    return (
        <>
            <NavigationSheetComponent
                isOpen={isOpen}
                setIsOpen={setIsOpen}
                title="Offer Letter Details"
                currentItem_Id={currentId}
                ForceItemLoad={forceLoad}
                dataList={DataList}
                reloadData={reloadData}
                allowEdit={false}
                allowDelete={false}
                fetchCurrentItemDetails={fetchData}
            >
                <DetailContent fields={fields} />
            </NavigationSheetComponent>
            {OpenSentOfferForm &&
                <SentOfferForm
                    isOpen={OpenSentOfferForm}
                    setIsOpen={() => {
                        setOpenSentOfferForm(false);
                    }}
                    initialData={FormData}
                />
            }
            {OpenManpowerForm && (
                <AddUpdateManpower
                    isOpen={OpenManpowerForm}
                    reloadData={() => {
                        setForceLoad(!forceLoad);
                        setOpenManpowerForm(false);
                    }}
                    setIsOpen={() => {
                        setOpenManpowerForm(false);
                    }}
                    edit_by_branch_dpt={true}
                    initialData={FormData}
                />
            )}
        </>
    );
};

export default ViewOfferGenerated;
