import React, { useState } from "react";
import {
    NavigationSheetComponent,
    DetailContent,
    StatusList,
} from "components";
import { FormatID, BranchName, DesignationName } from "utils/getValuesFromTables";
import { renderDate } from "utils/renderValues";
import { StatusLabel, StatusButtons } from "components";
import { getOfferLetterData, saveUpdateHeadcountRequest } from "app/hooks/talentSphere";
import { SentOfferForm } from "app/modules/TalentSphere";
import { EmployeeName } from "utils/getValuesFromTables";
import AttachmentUI from "components/ui/AttachmentUI";
import { Button } from "components/ui/button";

const ViewOfferGenerated = ({
    isOpen,
    setIsOpen,
    currentId,
    reloadData = () => { },
    DataList = [],
    ViewMode = false,
    isTeamView = false,
}) => {
    const [forceLoad, setForceLoad] = useState(false);
    const [FormData, setFormData] = useState({});
    const [OpenSentOfferForm, setOpenSentOfferForm] = useState(false);
    const handleSubmit = async (id, { comment }) => {
        try {
            await saveUpdateHeadcountRequest({ rejection_reason: comment }, id);
        } catch (error) {
            // Handle errors and rollback form data
            console.error(error);
        }
    };

    const handleSentApplicant = (event, data) => {
        event.preventDefault();
        event.stopPropagation();
        setFormData({ applicant: data.applicant, offer_letter: data.id })
        setOpenSentOfferForm(true);
    }
    // Define the fields to display
    const fields = [
        {
            customContent: true,
            renderContent: (data) => {
                return (
                    <div className="flex flex-wrap justify-end gap-2 items-center flex-wrap">
                        <StatusLabel className="ml-10" status={data.status}>
                            {data?.status?.toLowerCase()}
                        </StatusLabel>
                    </div>
                );
            },
        },
        {
            title: "Applicant Details",

            field: [
                {
                    key: "applicant",
                    label: "Applicant Id",
                    formatter: (cell, row) => <FormatID value={cell} prefix={"APP-"} />,
                },
                {
                    key: "candidate_name",
                    label: "Applicant Name",
                },
                {
                    key: "candidate_email",
                    label: "Email",
                },

                {
                    key: "candidate_contact",
                    label: "Contact Number",
                },
                {
                    key: "designation",
                    label: "Job Title",
                },
            ],
        },
        {
            title: "Offer Details",
            footerTitle: "Generated On",
            footerField: "generated_on",
            field: [
                {
                    key: "generated_by",
                    label: "Generated By",
                    formatter: (cell) => <EmployeeName value={cell} />
                },
                {
                    key: "offered_salary",
                    label: "Offered Salary",
                },
                {
                    key: "expected_joining_date",
                    label: "Joining Date",
                    formatter: (cell) => renderDate(cell),
                },
                {
                    key: "designation",
                    label: "Designation",
                },
                {
                    key: "work_location",
                    label: "Work Location",
                },
                {
                    key: "remarks",
                    label: "Remarks",
                },
            ],
        },
        {
            title: `Offer Letter`,
            field: [
                {
                    key: 'final_letter_pdf',
                    formatter: (cell, data) =>
                        cell ? (
                            <AttachmentUI
                                attachment={cell}
                                name={`Final Offer Letter`}
                                viewOnly={true}
                            />
                        ) : (
                            <div className="text-neutral-1000 text-sm">No document attached</div>
                        ),
                },
            ],
        },
        {
            title: "Approval Details",
            field: [
                {
                    key: "approval_details",
                    formatter: (cell) => (
                        <StatusList status_list={cell} className="my-3" />
                    ),
                },
            ],
        },
        {
            customContent: true,
            renderContent: (data) => {
                if (ViewMode || isTeamView) return null;
                if (data?.status?.toLowerCase() === 'approved')
                    return <Button className="flex justify-end mt-4" onClick={(event) => handleSentApplicant(event, data)}>Send to Applicant</Button>
                return (
                    <StatusButtons
                        permissionKey={'MANAGE_APPLICANT_OFFER_LETTER'}
                        status={data?.status}
                        current_approver={data.current_approver}
                        final_approver={data.final_approvers || []}
                        request_id={data.request}
                        RejectionConfig={{ label: 'Rejection Reason', required: true, }}
                        setResponse={async (response, _, approval_data) => {
                            if (response) {
                                await handleSubmit(data.id, approval_data);
                                setForceLoad(!forceLoad);
                            }
                        }}
                    />
                );
            },
        },
    ];

    const fetchData = async (id, isMounted) => {
        try {
            const response = await getOfferLetterData(id);
            if (isMounted) {
                return response;
            }
        } catch (error) {
            console.error("Error fetching roles:", error);
        }
    };

    return (
        <>
            <NavigationSheetComponent
                isOpen={isOpen}
                setIsOpen={setIsOpen}
                title="Offer Letter Details"
                currentItem_Id={currentId}
                ForceItemLoad={forceLoad}
                dataList={DataList}
                reloadData={reloadData}
                allowEdit={false}
                allowDelete={false}
                fetchCurrentItemDetails={fetchData}
            >
                <DetailContent fields={fields} />
            </NavigationSheetComponent>
            {OpenSentOfferForm &&
                <SentOfferForm
                    isOpen={OpenSentOfferForm}
                    setIsOpen={() => {
                        setOpenSentOfferForm(false);
                    }}
                    initialData={FormData}
                />
            }
        </>
    );
};

export default ViewOfferGenerated;
