import { EmployeePayrollColumns, EmployeePayslipColumns ,PayrunEmployeePayrollColumns,EmployeeAllowancesColumns,EmployeeDeductionsColumns} from "./PayrollTableColumns";
export { EmployeePayrollColumns, EmployeePayslipColumns,PayrunEmployeePayrollColumns ,EmployeeAllowancesColumns,EmployeeDeductionsColumns};
