# name: Deploy to Amazon ECS

# on:
#   workflow_dispatch: 
#   push:
#     branches: [ "main" ]

# env:
#   AWS_REGION: eu-west-1                              # set this to your preferred AWS region, e.g. us-west-1
#   ECR_REPOSITORY: hrms_prod_frontend                 # set this to your Amazon ECR repository name
#   ECS_SERVICE: hrms_prod_frontend_service            # set this to your Amazon ECS service name
#   ECS_CLUSTER: hrms_prod                             # set this to your Amazon ECS cluster name
#   ECS_TASK_DEFINITION: task-definition-prod.json     # set this to the path to your Amazon ECS task definition
#                                                      # file, e.g. .aws/task-definition.json
#   CONTAINER_NAME: hrms-prod_frontend                 # set this to the name of the container in the
#                                                      # containerDefinitions section of your task definition

# permissions:
#   contents: read

# jobs:
#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     environment: production

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ env.AWS_REGION }}

#     - name: Login to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v1

#     - name: Get Latest Image Digest
#       id: get-latest-digest
#       run: |
#         LATEST_DIGEST=$(aws ecr describe-images --repository-name $ECR_REPOSITORY --query 'imageDetails[?imageTags[0]==`new`].imageDigest' --output text)
#         echo "LATEST_DIGEST=$LATEST_DIGEST" >> $GITHUB_ENV

#     - name: List Images in ECR Repository
#       run: aws ecr list-images --repository-name $ECR_REPOSITORY

#     - name: Remove Old Images
#       run: |
#         LATEST_DIGEST=$LATEST_DIGEST
#         for IMAGE_DIGEST in $(aws ecr list-images --repository-name $ECR_REPOSITORY --query "imageIds[?imageDigest!='$LATEST_DIGEST'].imageDigest" --output text); do
#           aws ecr batch-delete-image --repository-name $ECR_REPOSITORY --image-ids imageDigest=$IMAGE_DIGEST
#         done

#     - name: Build, tag, and push image to Amazon ECR
#       id: build-image
#       env:
#         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#         IMAGE_TAG: new
#       run: |
#         # Build a docker container and
#         # push it to ECR so that it can
#         # be deployed to ECS.
#         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#         echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

#     - name: Fill in the new image ID in the Amazon ECS task definition
#       id: task-def
#       uses: aws-actions/amazon-ecs-render-task-definition@v1
#       with:
#         task-definition: ${{ env.ECS_TASK_DEFINITION }}
#         container-name: ${{ env.CONTAINER_NAME }}
#         image: ${{ steps.build-image.outputs.image }}

#     - name: Deploy Amazon ECS task definition
#       uses: aws-actions/amazon-ecs-deploy-task-definition@v1
#       with:
#         task-definition: ${{ steps.task-def.outputs.task-definition }}
#         service: ${{ env.ECS_SERVICE }}
#         cluster: ${{ env.ECS_CLUSTER }}
#         wait-for-service-stability: true
