name: Production Environment - Github Actions

# When this action will be executed.
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/production-pipeline.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Application
        run: npm run build
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HRMSPRODUCTIONFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HRMSPRODUCTIONFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HRMSPRODUCTIONFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Upload to Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode key --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} --source '$web'
            az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode key --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} --source ./dist --destination '$web'

      - name: Purge CDN
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths "/*" --profile-name ${{ secrets.CDN_PROFILE_NAME }} --name ${{ secrets.CDN_ENDPOINT_NAME }} --resource-group HRMS-AZURE
